context:
  version: "21.0.2"

package:
  name: cargo-update
  version: ${{ version }}

source:
  url: https://github.com/nabijaczleweli/cargo-update/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e67c56e727c85fbf2c51f0fda687ea153008ac4b9f9b501d2bee8c9e7f981c5e

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    content:
      # NOTE: currently, we have to omit `--locked` in `cargo install` since the upstream project has no `Cargo.lock` committed
      - if: unix
        then:
          - cargo auditable install --no-track --bins --root="$PREFIX" --path=.
      - if: win
        then:
          - cargo auditable install --no-track --bins --root="%LIBRARY_PREFIX%" --path=.
      - cargo-bundle-licenses --format=yaml --output=./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
  host:
    - if: unix
      then:
        - libgit2
        - openssl
        - pkg-config

tests:
  - script:
      - cargo install-update --help
      - cargo install-update --version
      - cargo help install-update
      - cargo install update --help
    requirements:
      run:
        - ${{ compiler('rust') }}
  - package_contents:
      bin:
        - cargo-install-update
        - cargo-install-update-config
      strict: true

about:
  summary: A cargo subcommand for checking and applying updates to installed executables
  description: |
    cargo-update provides the `cargo install-update` subcommand for cargo,
    allowing you to check for and apply updates to all installed cargo binaries.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/nabijaczleweli/cargo-update
  documentation: https://github.com/nabijaczleweli/cargo-update/tree/master/man
  repository: https://github.com/nabijaczleweli/cargo-update

extra:
  recipe-maintainers:
    - salim-b
