context:
  version: "22.1.1"

package:
  name: cargo-update
  version: ${{ version }}

source:
  url: https://github.com/nabijaczleweli/cargo-update/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 570d009f6ddd83d54ea478b63f369e08617feddb7119a9cb1d5c6a050d213c28

build:
  number: 1
  script:
    env:
      AWS_LC_SYS_CMAKE_BUILDER: ${{ "1" if win else "0" }} # force CMake builder for `aws-lc-sys` native C/C++ code on Windows
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      OPENSSL_NO_VENDOR: "1" # force linking to host's (conda-forge's) OpenSSL libs (on Unix)
      # instruct `cc` crate to use clang-cl natively to compile build-time tools intended to be run on the host when cross-compiling from `win_64`
      AR_x86_64_pc_windows_msvc: llvm-lib
      CC_x86_64_pc_windows_msvc: clang-cl
      CXX_x86_64_pc_windows_msvc: clang-cl
    content:
      # NOTE: we cannot use `--locked` in `cargo install` since the upstream project has no `Cargo.lock` committed
      - if: unix
        then:
          - export OPENSSL_DIR="$PREFIX" # force the correct OpenSSL libs dir to avoid pkg-config preferring the host's homebrew OpenSSL libs (on `osx_arm64` builders)
          - cargo auditable install --path=. --root="$PREFIX" --no-track --bins
      - if: win
        then:
          - cargo auditable install --path=. --root="%LIBRARY_PREFIX%" --no-track --bins
      - cargo-bundle-licenses --format=yaml --output=./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - if: win
      then: cmake
  host:
    - if: unix
      then:
        - libgit2
        - openssl
        - pkg-config
  run:
    - if: linux
      then: libsecret

tests:
  - script:
      - cargo-install-update --help
      - cargo-install-update --version
      - cargo-install-update-config --help
      - cargo-install-update-config --version
  - package_contents:
      bin:
        - cargo-install-update
        - cargo-install-update-config
      strict: true

about:
  summary: A cargo subcommand for checking and applying updates to installed executables
  description: |
    cargo-update provides the `cargo install-update` subcommand for cargo,
    allowing you to check for and apply updates to all installed cargo binaries.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/nabijaczleweli/cargo-update
  documentation: https://github.com/nabijaczleweli/cargo-update/tree/master/man
  repository: https://github.com/nabijaczleweli/cargo-update

extra:
  recipe-maintainers:
    - salim-b
